Code-review
fdfragoso/microReddit pull request #1
Opened 2020-09-11 07:06 UTC by keddo

2020-09-15 15:48 UTC, mikenath223 requested changes
This PR has been marked as invalid.

- Please add an appropriate description to this Pull Request.

2020-09-15 16:43 UTC, Dandush03 requested changes
# Status: :red_circle: Require Change :red_circle: 
### Great work so far, but sadly I see that you have some migration issue. I will post below what's causing it and proceed by reviewing your project.
# Have a Happy Coding

2020-09-15 16:43 UTC, Dandush03 commented on db/migrate/20200910154901_add_user_reference.rb
> +    add_column :users, :email, :string
## MIGRATION ERROR
The issue over here is that your line number 3 ends with a ','(comma) if you remove this, your migration should work with no issue. but I saw that below, you added again the email column to the user table. so you must delete the last file added to your migration that only contain the email

2020-09-15 16:43 UTC, Dandush03 commented on app/models/comment.rb
> +end
## Missing a Validation:
- [ ] Missing Body Validation

2020-09-15 16:43 UTC, Dandush03 commented on app/models/post.rb
> +end
## Missing Validations:
- [ ] Missing Title Validation
- [ ] Missing Body Validation

2020-09-15 16:43 UTC, Dandush03 commented on app/models/user.rb
> +end
## Missing Validations:
- [ ] Missing Email Validation

2020-09-16 09:56 UTC, maelfosso approved these changes
# Congratulations :clap: 

Thank you for applying the suggested changes.
The models are now OK. 
**PS**: You can merge it but please, fix the migrations errors before merging, by just removing that file or commenting the lines.

Good continuation :handshake: 

Mael FOSSO

2020-09-16 09:56 UTC, maelfosso commented on db/migrate/20200911080615_add_user_email.rb
> +  end
Error during the migrations
```rb
$ rails db:migrate
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
== 20200910135959 CreateComments: migrating ===================================
-- create_table(:comments)
   -> 0.0066s
== 20200910135959 CreateComments: migrated (0.0068s) ==========================

== 20200910140100 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0093s
== 20200910140100 CreateUsers: migrated (0.0095s) =============================

== 20200910140109 CreatePosts: migrating ======================================
-- create_table(:posts)
   -> 0.0150s
== 20200910140109 CreatePosts: migrated (0.0153s) =============================

== 20200910154901 AddUserReference: migrating =================================
-- add_reference(:comments, :user)
   -> 0.0128s
-- add_column(:users, :email, :string)
   -> 0.0094s
== 20200910154901 AddUserReference: migrated (0.0225s) ========================

== 20200911080615 AddUserEmail: migrating =====================================
-- add_column(:users, :email, :string)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: duplicate column name: email
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `initialize'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `new'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `prepare'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:193:in `execute'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:25:in `block (2 levels) in execute'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:24:in `block in execute'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:23:in `execute'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:591:in `add_column'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/sqlite3_adapter.rb:253:in `add_column'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:890:in `block in method_missing'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:858:in `block in say_with_time'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:858:in `say_with_time'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:879:in `method_missing'
/home/maelfosso/Documents/Microverse/TSE/RoR/microReddit/db/migrate/20200911080615_add_user_email.rb:3:in `change'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:828:in `exec_migration'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:811:in `block in migrate'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:810:in `migrate'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1002:in `migrate'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1310:in `block in execute_migration_in_transaction'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1361:in `block in ddl_transaction'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/transactions.rb:212:in `transaction'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1361:in `ddl_transaction'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/home/maelfosso/.rvm/gems/ruby-2.7.1/gems/ [...]

2020-09-16 09:56 UTC, maelfosso commented on db/migrate/20200911080615_add_user_email.rb
> +    add_column :users, :email, :string
Comment that line or remove that file for the migration to be successful

2020-09-16 12:33 UTC, merged